### PR TITLE
new Proto::Array class

### PR DESCRIPTION
**Pull request by dwatersg**
only what's needed for the `AMRFAS` example to build has been written so far. I know things like dot products were also requested.

### CODE REVIEW

**Review by cgebhart-lbl — COMMENTED** [review]
When adding the #include statements to Proto.H or any of the other master headers, do your best to place them as high up in the list as possible. Because we are a header only, the order here matters and can lead to obnoxiously obtuse linking errors.

**Review by cgebhart-lbl — CHANGES_REQUESTED** [review]
I would like to see either an explicit `ArrayTests` file added to tests, or a proxy test added to `ForallTests` that exercises Array as an input to a forall call both on the CPU and GPU.

**Review by cgebhart-lbl — CHANGES_REQUESTED** [review]
the const versions of Array::begin() and Array::end() should not have different names. The trailing "const" provides the necessary disambiguation

Why has Operator::_deconvolve(LevelBoxData...) been commented out? Are these changes from Phil's work?

**Comment by dwatersg** [comment]
All four iterators are const: only one begin and one end iterator return `const` iterators though, so to distinguish them from the regular ones I prepended them with 'c'.

Regarding the second comment, there was a mistake I made when merging upstream branches that resulted in commits made to them since the inception of this branch being included in the PR. That has been fixed: you'll see that `Proto_Operator.H` is no longer part of the PR.

**Pull request merged**
